---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012R2

suites:
  - name: client
    run_list:
      - recipe[sql_server::default]
    attributes: { sql_server: { accept_eula: true } }
  - name: server2016
    run_list:
      - recipe[sql_server::server]
    attributes: { sql_server: { accept_eula: true, version: 2016, server_sa_password: Supersecurepassword123 } }
    
